Feature/gripper skeleton
Team488/TeamXbot2019 pull request #5
Opened 2019-01-25 04:23 UTC by sachifig

Gripper subsystem skeleton contains GrabDiscCommand, ReleaseDiscCommand, test files for each command, and subsystem class.

2019-01-25 04:46 UTC, JohnGilb requested changes

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/GripperSubsystem.java
> +            diskSensor = clf.createDigitalInput(-1);
You should get this from the contract. Also, do the same setInverted call as above.

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/GripperSubsystem.java
> +
remove this blank line

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/GripperSubsystem.java
> +
remove this blank line

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/GripperSubsystem.java
> +
remove this blank line

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/commands/GrabDiscCommand.java
> +        gripperSubsystem=gripper;
add some spaces, so `gripperSubsystem = gripper;`

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/main/java/competition/subsystems/gripper/commands/ReleaseDiscCommand.java
> +        gripperSubsystem=gripper;
Same as above

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/test/java/competition/subsystems/gripper/GrabDiscCommandTest.java
> +        gripperSubsystem.grabHatch();
This method doesn't actually use the GrabDiscCommand. You should call `GrabDiscCommand.initialize()`

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/test/java/competition/subsystems/gripper/GripperSubsystemTest.java
> +        gripperSubsystem.grabHatch();
before this line, check to make sure the gripper is set off.

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/test/java/competition/subsystems/gripper/GripperSubsystemTest.java
> +        gripperSubsystem.releaseHatch();
before this line, check to make sure the gripper is set on.

2019-01-25 04:46 UTC, JohnGilb commented on Competition/src/test/java/competition/subsystems/gripper/ReleaseDiscCommandTest.java
> +        gripperSubsystem.releaseHatch();
You need to use the Command, not the Subsystem (see my other comments on the other command test)

2019-02-02 19:34 UTC, sachifig commented
@JohnGilb We finished editing.

2019-02-09 20:36 UTC, merged