Feature/small changes
Team488/TeamXbot2019 pull request #88
Opened 2019-03-15 01:39 UTC by davidVespa

2019-03-15 01:55 UTC, JohnGilb requested changes

2019-03-15 01:55 UTC, JohnGilb commented on Competition/src/main/java/competition/commandgroups/drivecommandgroups/DriveToNearestLoadingStationCommandGroup.java
> +        if (setPose.getSide() == Side.Right) {
This isn't going to work - the left/right properties are set at the moment of creation. We'll need to talk about how to do this.

2019-03-16 23:16 UTC, aschokking commented
It looks like the tests are failing on this branch and the there are a few merge conflicts to take a peek at?

2019-03-20 02:23 UTC, JohnGilb approved these changes

2019-03-20 03:06 UTC, merged